presidential_facts/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

resources :presidents
  root 'welcome#index'

end

presidential_facts/app/models/president.rb
class President < ActiveRecord::Base
  validates :name, presence: true,
                    length: { minimum: 5 }
end

presidential_facts/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

presidential_facts/app/controllers/presidents_controller.rb
class PresidentsController < ApplicationController
  def index
    @presidents = President.all
  end

  def show
    @president = President.find(params[:id])
  end

  def new
    @president = President.new
  end

  def edit
    @president = President.find(params[:id])
  end

  def create
    @president = President.new(president_params)
    if @president.save
      redirect_to @president
    else
      render 'new'
    end
  end

  def update
    @president = President.find(params[:id])

    if @president.update(president_params)
      redirect_to @president
    else
      render 'edit'
    end
  end

def destroy
  @president = President.find(params[:id])
  @president.destroy

  redirect_to presidents_path
end

  private
  def president_params
    params.require(:president).permit(:name, :text)
  end

  #   @president = President.new(params.require(:president).permit(:name, :text)
  #   # render plain: params[:president].inspect
  #   @president.save
  #   redirect_to @president
  # end

end

presidential_facts/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

presidential_facts/app/helpers/application_helper.rb
module ApplicationHelper
end

presidential_facts/app/helpers/presidents_helper.rb
module PresidentsHelper
end

presidential_facts/app/helpers/welcome_helper.rb
module WelcomeHelper
end

presidential_facts/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PresidentialFacts</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

presidential_facts/app/views/presidents/_form.html.erb
<%= form_for @president do |f| %>

  <% if @president.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@presdient.errors.count, "error") %> prohibited
        this presdient from being saved:
      </h2>
      <ul>
        <% @president.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :facts %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

presidential_facts/app/views/presidents/edit.html.erb
<h1> Edit president>

  <%= render 'form' %>

  <%= link_to 'Back', presidents_path %>

<!-- <h1>Editing president</h1>

<%= form_for :president, url: president_path(@president), method: :patch do |f| %>

  <% if @president.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@president.errors.count, "error") %> prohibited
        this president from being saved:
      </h2>
      <ul>
        <% @president.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :text %>
  </p>

  <p>
    <%= f.label :facts %><br>
    <%= f.text_area :text %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

<%= link_to 'Back', presidents_path %> -->

presidential_facts/app/views/presidents/index.html.erb
<h1>Listing of presidents</h1>

<%= link_to 'New president', new_president_path %>
<table>
  <tr>
    <th>Name</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>

  <% @presidents.each do |president| %>
    <tr>
      <td><%= president.name %></td>
      <td><%= president.text %></td>
      <td><%= link_to 'Show', president_path(president) %></td>
      <td><%= link_to 'Edit', edit_president_path(president) %></td>
      <td><%= link_to 'Destroy', president_path(president),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

presidential_facts/app/views/presidents/new.html.erb
<h1> New president</h1>

<%= render 'form' %>

<%= link_to 'Back', presidents_path %>


<!-- # <%= form_for :president, url: presidents_path do |f| %>
#     <% if @president.errors.any? %>
#     <div id ="error_explanation">
#       <h2>
#         <%= pluralize(@president.errors.count, "error") %> prohibited
#       this president from being saved:
#     </h2>
#     <ul>
#       <% @president.errors.full_messages.each do |msg| %>
#         <li><%= msg %></li>
#       <% end %>
#     </ul>
#   </div>
# <% end %>
#
#   <p>
#     <%= f.label :name %><br>
#     <%= f.text_field :name %>
#   </p>
#
#   <p>
#     <%= f.label :facts %><br>
#     <%= f.text_area :text %>
#   </p>
#
#   <p>
#     <%= f.submit %>
#   </p>
# <% end %>
#
# <%= link_to 'Back', presidents_path %> -->

presidential_facts/app/views/presidents/show.html.erb
<p>
  <strong>Name</strong>
  <%= @president.name %>
</p>

<p>
  <strong>Text</strong>
  <%= @president.text %>
</p>
<%= link_to 'Edit', edit_president_path(@president) %> |
<%= link_to 'Back', presidents_path %>

presidential_facts/app/views/welcome/index.html.erb
<body>
<h1> A Database of Presidential Facts</h1>
<div><%= link_to 'Database', controller: 'presidents' %></div>



<img src = https://upload.wikimedia.org/wikipedia/commons/b/b6/Gilbert_Stuart_Williamstown_Portrait_of_George_Washington.jpg "George Washington"</img>
<img src = https://upload.wikimedia.org/wikipedia/commons/f/f2/Abraham_Lincoln_O-55,_1861-crop.jpg </img>
<img src = http://www.old-picture.com/american-legacy/004/pictures/President-Woodrow-Wilson-002.jpg </img>

</body>